### ISSUE TITLE
[330a5f] qtapp.exe: issue_debug_notification, terminate, FindHandler<__FrameHandler3>, thread_start<unsigned int (__stdcall*)...

### ISSUE THREAD

**Issue by kenkit** [kenkit/neon_service#168]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><b><a href="https://neon.sp.backtrace.io/dashboard/neon/project/qtapp/group/330a5f3cbc4951b5b4295e08b7c1e388a7f8f9c1c341d470b02f5c3d6923f3b7">New error: [qtapp]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>qtapp.exe</td></tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>breakpoint</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
issue_debug_notification
terminate
FindHandler&lt;__FrameHandler3&gt;
thread_start&lt;unsigned int (__stdcall*)(void *),1&gt;</code>
        </td>
    </tr></table>

**Comment by gr01d** [comment]
Hi, this is not an issue but I need your response regarding this thread on sourceforge (clam sentinel), the link indicated is now dead. I want to know what progress have you made?
https://sourceforge.net/p/clamsentinel/discussion/976132/thread/e3f91b8d/?limit=25&page=2

**Comment by gr01d** [comment]
Care to answer my question?

**Comment by kenkit** [comment]
Yes, how may I assist you @gr01d  ?

**Comment by gr01d** [comment]
Hi, I need your response regarding this thread on sourceforge (clam sentinel), the link indicated is now dead. I want to know what progress have you made?
https://sourceforge.net/p/clamsentinel/discussion/976132/thread/e3f91b8d/?limit=25&page=2

years ago, you planned to create an real time av for the clamwin/clam sentinel, check the link above it has your name on it.

**Comment by kenkit** [comment]
@gr01d You should've just opened a new issue. I must have missed seeing your comment since this issue as autocreated by my app.
About that Platonic AV.  Alot of things came up and I had to halt working on it.
But I discovered I will need to add it to this project in order to verify the authenticity of files my project uses and users might add later on.
This is so because this software is decentralized and will eventually have to execute custom commands on users pc.
E.g I some of this commands will rely on adb.exe. The software will have to ensure that such binaries don't contain malware that a malicious user can modify inorder to manipulate my users machins.
If I don't do this then I ran the risk of distributing malware to my users.

**Comment by kenkit** [comment]
You can find it under the projects tab here https://github.com/kenkit/neon_service/projects/1#card-51982773

**Comment by kenkit** [comment]
btw I wasn't creating it for ClamAv. It was a separate project aimed at replacing ClamAV

**Comment by gr01d** [comment]
Thanks for your response, yeah ClamAV appears to be abandoned. There is only at least one person developing it as of now.

**Comment by kenkit** [comment]
Ok, do you intend to start working on an AV engine?

**Comment by gr01d** [comment]
Not really, just trying to create a real time protection to clamav/clamwin.
